version: '3'

services:
  back:
    build: back/
    restart: always
    environment:
    - VIRTUAL_HOST=backend
    - VIRTUAL_PROTO=uwsgi
    - VIRTUAL_PORT=5000
    ports:
    - 8080
    networks:
    - production

  front:
    image: 'nginx:stable'
    restart: always
    environment:
    - VIRTUAL_HOST=frontend
    ports:
    - 80:80
    volumes:
    - ./front:/usr/share/nginx/html
    networks:
    - production
    links:
    - "back"

  mysql:
    restart: always
    image: mysql:5.7.32
    ports:
    - "127.0.0.1:3398:3306"
    environment:
    - MYSQL_DATABASE=database
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=root_password
    - MYSQL_HOST=%
    - MYSQL_ROOT_HOST=%
    volumes:
    - ./mysql:/var/lib/mysql
    networks:
    -  production 

networks:
  production:
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.249.0/24